const DATA_EXTRACTED_FOLDER = "dataextracted";
const DATA_EXTRACTED_PRODUCT_FILE = "productData";
const DATA_EXTRACTED_QUESTIONS_FILE = "questions";
const DATA_EXTRACTED_REVIEWS_FILE = "reviews";


const DATA_TRANSFORMED_FOLDER = "datatransformed";
const DATA_TRANSFORMED_PRODUCT_FILE = "productTransformed";
const DATA_TRANSFORMED_QUESTIONS_FILE = "questionsTransformed";
const DATA_TRANSFORMED_QUESTIONS_ANSWER_FILE = "questionAnswersTransformed";
const DATA_TRANSFORMED_REVIEWS_FILE = "reviewsTransformed";
const DATA_TRANSFORMED_REVIEWS_COMMENTS_FILE = "reviewCommentsTransformed";


module.exports = {
    DATA_EXTRACTED_FOLDER, DATA_TRANSFORMED_FOLDER,
    DATA_EXTRACTED_PRODUCT_FILE, DATA_EXTRACTED_QUESTIONS_FILE, DATA_EXTRACTED_REVIEWS_FILE,
    DATA_TRANSFORMED_PRODUCT_FILE, DATA_TRANSFORMED_QUESTIONS_FILE, DATA_TRANSFORMED_QUESTIONS_ANSWER_FILE,
    DATA_TRANSFORMED_REVIEWS_FILE, DATA_TRANSFORMED_REVIEWS_COMMENTS_FILE
};